import type { Job } from "@/types";

export interface JobWithCompany extends Job {
  company_name: string;
  company_slug: string;
  company_score: number;
  company_industry: string;
  requirements?: string[];
  benefits?: string[];
}

export const demoJobs: JobWithCompany[] = [
  {
    id: "job-1",
    company_id: "comp-1",
    company_name: "Infobip",
    company_slug: "infobip",
    company_score: 8.4,
    company_industry: "Tech",
    title: "Senior Frontend Developer",
    description: "Tražimo iskusnog frontend developera koji će raditi na našoj komunikacijskoj platformi korištenoj od strane najvećih svjetskih brandova. Radit ćeš u agilnom timu od 6 ljudi na razvoju korisničkog sučelja koristeći React i TypeScript. Nudimo fleksibilno radno vrijeme, rad od kuće i priliku za rad na proizvodu koji koriste milijuni korisnika.",
    requirements: [
      "5+ godina iskustva s React/TypeScript",
      "Poznavanje Next.js frameworka",
      "Iskustvo s REST i GraphQL API-jevima",
      "Timski igrač s dobrim komunikacijskim vještinama",
    ],
    benefits: [
      "Fleksibilno radno vrijeme",
      "Rad od kuće 3 dana tjedno",
      "Privatno zdravstveno osiguranje",
      "Edukacijski budžet 2.000€ godišnje",
      "Multisport kartica",
    ],
    job_type: "full-time",
    remote_policy: "hybrid",
    salary_min: 3500,
    salary_max: 5500,
    city: "Zagreb",
    country_code: "HR",
    is_promoted: true,
    created_at: "2025-07-20T10:00:00Z",
  },
  {
    id: "job-2",
    company_id: "comp-2",
    company_name: "Lek d.d.",
    company_slug: "lek-dd",
    company_score: 8.7,
    company_industry: "Farmacija",
    title: "Kontrolor kvalitete u proizvodnji",
    description: "Pridruži se našem timu u Ljubljanom pogonu. Kao kontrolor kvalitete bit ćeš odgovoran za praćenje kvalitete u procesu proizvodnje lijekova, provođenje inspekcija i dokumentiranje rezultata. Tražimo pedantnu osobu s iskustvom u farmaceutskoj ili prehrambenoj industriji.",
    requirements: [
      "VSS farmacija, kemija ili srodan smjer",
      "2+ godine iskustva u kontroli kvalitete",
      "Poznavanje GMP standarda",
      "Znanje slovenskog ili engleskog jezika",
    ],
    benefits: [
      "Stabilno zaposlenje u Novartis grupi",
      "13. plaća + božićnica",
      "Subvencionirani obroci",
      "Organizirani prijevoz",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 2200,
    salary_max: 3000,
    city: "Ljubljana",
    country_code: "SI",
    is_promoted: false,
    created_at: "2025-07-19T14:00:00Z",
  },
  {
    id: "job-3",
    company_id: "comp-3",
    company_name: "Rimac Technology",
    company_slug: "rimac-technology",
    company_score: 7.9,
    company_industry: "Automotive",
    title: "Battery Systems Engineer",
    description: "Rimac traži inženjera baterijskih sustava za rad na sljedećoj generaciji električnih hiperautomobila. Radit ćeš na dizajnu, testiranju i optimizaciji baterijskih paketa. Pridruži se timu koji mijenja budućnost automobilske industrije.",
    requirements: [
      "Diplomirani inženjer elektrotehnike ili strojarstva",
      "3+ godine iskustva s baterijskim sustavima",
      "Poznavanje CAD alata (CATIA/SolidWorks)",
      "Tečan engleski jezik",
    ],
    benefits: [
      "Rad na cutting-edge tehnologiji",
      "Konkurentna plaća + bonusi",
      "Fleksibilno radno vrijeme",
      "Kantina s subvencioniranim obrocima",
      "Team building eventi",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 3000,
    salary_max: 5000,
    city: "Zagreb",
    country_code: "HR",
    is_promoted: true,
    created_at: "2025-07-18T09:00:00Z",
  },
  {
    id: "job-4",
    company_id: "comp-4",
    company_name: "Nordeus",
    company_slug: "nordeus",
    company_score: 8.1,
    company_industry: "Gaming",
    title: "Game Designer",
    description: "Nordeus, kreator Top Eleven — najpopularnije sportske mobilne igre, traži kreativnog game designera. Radit ćeš na novim mehanikama igre, balansiranju gameplay-a i kreiranju engaging iskustva za igrače diljem svijeta.",
    requirements: [
      "3+ godine iskustva u game designu",
      "Portfolio s objavljenim igrama",
      "Razumijevanje free-to-play monetizacije",
      "Analitičko razmišljanje i ljubav prema igrama",
    ],
    benefits: [
      "Rad na igri s 200M+ preuzimanja",
      "Ured u centru Beograda",
      "Neograničeni godišnji odmor",
      "Gaming soba u uredu",
      "Fitness članarina",
    ],
    job_type: "full-time",
    remote_policy: "hybrid",
    salary_min: 2500,
    salary_max: 4000,
    city: "Beograd",
    country_code: "RS",
    is_promoted: false,
    created_at: "2025-07-17T11:00:00Z",
  },
  {
    id: "job-5",
    company_id: "comp-5",
    company_name: "Konzum d.d.",
    company_slug: "konzum",
    company_score: 5.2,
    company_industry: "Retail",
    title: "Voditelj poslovnice",
    description: "Konzum traži voditelja poslovnice za novu lokaciju u Splitu. Odgovornosti uključuju upravljanje timom od 15+ zaposlenika, kontrolu zaliha, postizanje prodajnih ciljeva i osiguravanje vrhunske korisničke usluge.",
    requirements: [
      "3+ godine iskustva u maloprodaji",
      "Iskustvo u vođenju tima",
      "Poznavanje retail procesa i inventure",
      "Vozačka dozvola B kategorije",
    ],
    benefits: [
      "Popusti za zaposlenike",
      "Božićnica i regres",
      "Mogućnost napredovanja",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1200,
    salary_max: 1600,
    city: "Split",
    country_code: "HR",
    is_promoted: false,
    created_at: "2025-07-16T08:00:00Z",
  },
  {
    id: "job-6",
    company_id: "comp-6",
    company_name: "Triglav Osiguranje",
    company_slug: "triglav",
    company_score: 7.1,
    company_industry: "Financije",
    title: "Aktuarski analitičar",
    description: "Zavarovalnica Triglav traži aktuarskog analitičara za tim u Ljubljani. Bavit ćeš se procjenom rizika, kreiranjem modela i analizom podataka za potrebe osiguranja. Idealna pozicija za matematičare i statističare koji žele karijeru u financijskom sektoru.",
    requirements: [
      "Diploma iz matematike, statistike ili aktuarstva",
      "Poznavanje Python/R za analizu podataka",
      "Analitičko razmišljanje i preciznost",
      "Znanje slovenskog jezika prednost",
    ],
    benefits: [
      "Stabilno zaposlenje u vodećem osiguratelju",
      "Podrška za aktuarske ispite",
      "Rad od kuće 2 dana tjedno",
      "Dodatno mirovinsko osiguranje",
    ],
    job_type: "full-time",
    remote_policy: "hybrid",
    salary_min: 2500,
    salary_max: 3500,
    city: "Ljubljana",
    country_code: "SI",
    is_promoted: false,
    created_at: "2025-07-15T13:00:00Z",
  },
  {
    id: "job-7",
    company_id: "comp-7",
    company_name: "BH Telecom",
    company_slug: "bh-telecom",
    company_score: 6.3,
    company_industry: "Telekomunikacije",
    title: "Mrežni inženjer",
    description: "BH Telecom traži mrežnog inženjera za rad na održavanju i unapređenju telekomunikacijske infrastrukture. Radit ćeš na projektima 5G mreže i fiber optike u Sarajevu i okolici.",
    requirements: [
      "Diploma iz informatike ili elektrotehnike",
      "CCNA ili ekvivalentna certifikacija",
      "Iskustvo s Cisco i Huawei opremom",
      "Spremnost za rad na terenu",
    ],
    benefits: [
      "Besplatna mobilna pretplata",
      "Jubilarni bonusi",
      "Organizirani prijevoz",
      "Profesionalni razvoj i certifikacije",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1800,
    salary_max: 2500,
    city: "Sarajevo",
    country_code: "BA",
    is_promoted: false,
    created_at: "2025-07-14T10:00:00Z",
  },
  {
    id: "job-8",
    company_id: "comp-8",
    company_name: "Nelt Grupa",
    company_slug: "nelt-grupa",
    company_score: 6.8,
    company_industry: "Logistika",
    title: "Logistički koordinator",
    description: "Nelt Grupa traži logističkog koordinatora za distribucijski centar u Beogradu. Odgovornosti uključuju koordinaciju transporta, upravljanje skladištem i optimizaciju lanaca opskrbe za poznate FMCG brendove.",
    requirements: [
      "2+ godine iskustva u logistici",
      "Poznavanje WMS sustava",
      "Organizacijske sposobnosti",
      "Vozačka dozvola B kategorije",
    ],
    benefits: [
      "Bonusi za učinak",
      "Obuka i razvoj",
      "Korporativna mobilna pretplata",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1000,
    salary_max: 1500,
    city: "Beograd",
    country_code: "RS",
    is_promoted: false,
    created_at: "2025-07-13T09:00:00Z",
  },
  {
    id: "job-9",
    company_id: "comp-9",
    company_name: "Outfit7",
    company_slug: "outfit7",
    company_score: 7.6,
    company_industry: "Tech",
    title: "Data Scientist",
    description: "Outfit7, kreator Talking Tom-a, traži Data Scientista za ured u Ljubljani. Analizirat ćeš podatke o ponašanju korisnika, razvijati ML modele za personalizaciju i pomagati u donošenju product odluka temeljenih na podacima.",
    requirements: [
      "Magisterij iz matematike, statistike ili CS",
      "Iskustvo s Python, SQL, scikit-learn",
      "Razumijevanje A/B testiranja",
      "Iskustvo u mobilnoj industriji prednost",
    ],
    benefits: [
      "Ured s pogledom na Alpe",
      "Fleksibilno radno vrijeme",
      "Stock opcije",
      "Besplatna hrana u uredu",
      "Pet-friendly ured",
    ],
    job_type: "full-time",
    remote_policy: "hybrid",
    salary_min: 3000,
    salary_max: 4500,
    city: "Ljubljana",
    country_code: "SI",
    is_promoted: true,
    created_at: "2025-07-12T15:00:00Z",
  },
  {
    id: "job-10",
    company_id: "comp-10",
    company_name: "ASA Group",
    company_slug: "asa-group",
    company_score: 6.5,
    company_industry: "Automotive",
    title: "Prodajni predstavnik — vozila",
    description: "ASA Group, vodeći distributer automobila u BiH, traži prodajnog predstavnika za salon u Sarajevu. Odgovornosti uključuju savjetovanje kupaca, prezentaciju vozila i postizanje mjesečnih prodajnih ciljeva.",
    requirements: [
      "Iskustvo u prodaji (poželjno auto industrija)",
      "Odlične komunikacijske vještine",
      "Poznavanje tržišta automobila",
      "Vozačka dozvola B kategorije",
    ],
    benefits: [
      "Osnovna plaća + provizija",
      "Službeno vozilo",
      "Obuka od strane proizvođača",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1200,
    salary_max: 2500,
    city: "Sarajevo",
    country_code: "BA",
    is_promoted: false,
    created_at: "2025-07-11T11:00:00Z",
  },
  {
    id: "job-11",
    company_id: "comp-11",
    company_name: "Span d.d.",
    company_slug: "span",
    company_score: 7.8,
    company_industry: "Tech",
    title: "Cloud Solutions Architect",
    description: "Span traži Cloud Solutions Architecta za dizajn i implementaciju cloud rješenja za enterprise klijente. Radit ćeš s Azure i AWS platformama, voditi tehničke prezentacije i mentorirati juniore u timu.",
    requirements: [
      "5+ godina iskustva s cloud platformama",
      "Azure/AWS certifikacije",
      "Iskustvo s IaC (Terraform/Pulumi)",
      "Odlične prezentacijske vještine",
    ],
    benefits: [
      "Certificirani Microsoft partner",
      "Budžet za certifikacije",
      "Remote-first kultura",
      "Privatno zdravstveno",
      "Konferencijski budžet",
    ],
    job_type: "full-time",
    remote_policy: "remote",
    salary_min: 4000,
    salary_max: 6000,
    city: "Zagreb",
    country_code: "HR",
    is_promoted: false,
    created_at: "2025-07-10T08:00:00Z",
  },
  {
    id: "job-12",
    company_id: "comp-12",
    company_name: "Mercator",
    company_slug: "mercator",
    company_score: 5.8,
    company_industry: "Retail",
    title: "Skladištar — noćna smjena",
    description: "Mercator traži skladištare za rad u noćnoj smjeni u distribucijskom centru Ljubljana. Posao uključuje prijem robe, sortiranje, slaganje i pripremu narudžbi za dostavu u poslovnice.",
    requirements: [
      "Fizička kondicija za rad u skladištu",
      "Spremnost za rad u noćnoj smjeni",
      "Vozačka dozvola za viličar (prednost)",
      "Pouzdanost i timski rad",
    ],
    benefits: [
      "Noćni dodatak 30%",
      "Topli obrok osiguran",
      "Organizirani prijevoz",
      "Popusti u Mercator trgovinama",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1300,
    salary_max: 1700,
    city: "Ljubljana",
    country_code: "SI",
    is_promoted: false,
    created_at: "2025-07-09T16:00:00Z",
  },
  {
    id: "job-13",
    company_id: "comp-13",
    company_name: "FIS d.o.o.",
    company_slug: "fis",
    company_score: 7.2,
    company_industry: "Tech",
    title: "Junior Java Developer",
    description: "FIS traži junior Java developera za ured u Sarajevu. Pridruži se timu koji razvija bankarske softverske sustave za klijente u regiji. Idealna pozicija za početak karijere u fintech-u s mentoringom od seniornih kolega.",
    requirements: [
      "Diploma iz informatike ili srodnog smjera",
      "Osnovno znanje Jave i SQL-a",
      "Spremnost za učenje i razvoj",
      "Poznavanje Git-a prednost",
    ],
    benefits: [
      "Strukturirani onboarding program",
      "Mentoring od seniora",
      "Edukacijski budžet",
      "Mlad i dinamičan tim",
    ],
    job_type: "full-time",
    remote_policy: "hybrid",
    salary_min: 1200,
    salary_max: 1800,
    city: "Sarajevo",
    country_code: "BA",
    is_promoted: false,
    created_at: "2025-07-08T12:00:00Z",
  },
  {
    id: "job-14",
    company_id: "comp-14",
    company_name: "Slovenijales",
    company_slug: "slovenijales",
    company_score: 6.9,
    company_industry: "Proizvodnja",
    title: "CNC operater",
    description: "Slovenijales traži CNC operatera za pogon u Slovenj Gradcu. Radit ćeš na modernim CNC strojevima za obradu drva i kompozitnih materijala. Nudimo stabilno zaposlenje i mogućnost usavršavanja.",
    requirements: [
      "Srednja stručna sprema (strojarstvo ili drvoprerada)",
      "Iskustvo s CNC strojevima",
      "Sposobnost čitanja tehničke dokumentacije",
      "Preciznost i odgovornost",
    ],
    benefits: [
      "Stabilna plaća + dodaci",
      "Topli obrok i prijevoz",
      "Božićnica",
      "Rad u jednoj smjeni",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 1500,
    salary_max: 2000,
    city: "Slovenj Gradec",
    country_code: "SI",
    is_promoted: false,
    created_at: "2025-07-07T07:00:00Z",
  },
  {
    id: "job-15",
    company_id: "comp-15",
    company_name: "Vega IT",
    company_slug: "vega-it",
    company_score: 8.3,
    company_industry: "Tech",
    title: "UX/UI Designer",
    description: "Vega IT, jedna od najbolje ocijenjenih IT tvrtki u Srbiji, traži UX/UI dizajnera za projekte s međunarodnim klijentima. Radit ćeš na web i mobilnim aplikacijama, provoditi korisničko istraživanje i kreirati wireframe-ove i prototipove.",
    requirements: [
      "3+ godine iskustva u UX/UI dizajnu",
      "Portfolio s web/mobile projektima",
      "Poznavanje Figme i design sustava",
      "Razumijevanje accessibility standarda",
    ],
    benefits: [
      "Glassdoor ocjena 4.8/5",
      "Rad od kuće ili iz ureda",
      "Privatno zdravstveno osiguranje",
      "Retreat-ovi i team building",
      "Edukacijski budžet bez limita",
    ],
    job_type: "full-time",
    remote_policy: "remote",
    salary_min: 2000,
    salary_max: 3500,
    city: "Novi Sad",
    country_code: "RS",
    is_promoted: true,
    created_at: "2025-07-06T10:00:00Z",
  },
  {
    id: "job-16",
    company_id: "comp-16",
    company_name: "Croatia Airlines",
    company_slug: "croatia-airlines",
    company_score: 5.5,
    company_industry: "Transport",
    title: "Agent korisničke podrške",
    description: "Croatia Airlines traži agenta korisničke podrške za rad u call centru na Zračnoj luci Zagreb. Odgovornosti uključuju odgovaranje na upite putnika, rješavanje reklamacija i pomoć pri rezervacijama.",
    requirements: [
      "Tečan engleski + poželjno još jedan strani jezik",
      "Iskustvo u korisničkoj podršci",
      "Komunikativnost i strpljivost",
      "Spremnost za rad u smjenama",
    ],
    benefits: [
      "Popusti na letove do 90%",
      "Smjenski dodaci",
      "Prilika za putovanja",
    ],
    job_type: "full-time",
    remote_policy: "onsite",
    salary_min: 900,
    salary_max: 1200,
    city: "Zagreb",
    country_code: "HR",
    is_promoted: false,
    created_at: "2025-07-05T14:00:00Z",
  },
  {
    id: "job-17",
    company_id: "comp-17",
    company_name: "Comtrade",
    company_slug: "comtrade",
    company_score: 7.0,
    company_industry: "Tech",
    title: "DevOps Engineer",
    description: "Comtrade traži DevOps inženjera za projekte s klijentima iz Silicon Valley-a. Radit ćeš na automatizaciji CI/CD pipeline-ova, upravljanju Kubernetes klasterima i monitoringu produkcijskih sustava.",
    requirements: [
      "3+ godine DevOps iskustva",
      "Kubernetes, Docker, Terraform",
      "Iskustvo s AWS ili GCP",
      "Scripting (Bash, Python)",
    ],
    benefits: [
      "Rad s US klijentima",
      "Kompetitivna plaća",
      "Remote opcija",
      "Konferencije i certifikacije",
    ],
    job_type: "full-time",
    remote_policy: "remote",
    salary_min: 2200,
    salary_max: 3800,
    city: "Beograd",
    country_code: "RS",
    is_promoted: false,
    created_at: "2025-07-04T09:00:00Z",
  },
];

export function getJobs(filters?: {
  country?: string;
  city?: string;
  industry?: string;
  jobType?: string;
  salaryMin?: number;
  minRating?: number;
  search?: string;
}): JobWithCompany[] {
  let results = [...demoJobs];

  if (filters?.country) {
    results = results.filter((j) => j.country_code === filters.country);
  }
  if (filters?.city) {
    results = results.filter((j) =>
      j.city.toLowerCase().includes(filters.city!.toLowerCase())
    );
  }
  if (filters?.industry) {
    results = results.filter((j) => j.company_industry === filters.industry);
  }
  if (filters?.jobType) {
    results = results.filter((j) => j.job_type === filters.jobType);
  }
  if (filters?.salaryMin) {
    results = results.filter(
      (j) => j.salary_max && j.salary_max >= filters.salaryMin!
    );
  }
  if (filters?.minRating) {
    results = results.filter((j) => j.company_score >= filters.minRating!);
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase();
    results = results.filter(
      (j) =>
        j.title.toLowerCase().includes(q) ||
        j.company_name.toLowerCase().includes(q) ||
        j.description.toLowerCase().includes(q)
    );
  }

  return results;
}
